# -*- coding: utf-8 -*-
"""complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/shauryajain111/Deep-JSCC/blob/main/complete.ipynb
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import os, re, cv2
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

import numpy as np, os, re, io, warnings
import matplotlib.pyplot as plt
from PIL import Image
from scipy.special import erfc
import tensorflow as tf
from tensorflow.keras import layers, models
warnings.filterwarnings('ignore')

print("GPU:", tf.test.gpu_device_name() or "⚠ No GPU — Runtime → T4 GPU")
print("TF :", tf.__version__)

# Run this to find your dataset path
import os

# ─── CELL 2 | Load Dataset (FIXED) ───────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, re
import numpy as np
from PIL import Image

DATA_DIR   = '/content/drive/MyDrive/Colab Notebooks/dataset/npy_chunks/'
RESIZE_TO  = 64     # resize from 224×224 → 64×64 to save RAM

# Load ONLY X_batch files (skip y_batch label files)
x_files = sorted(
    [f for f in os.listdir(DATA_DIR) if f.startswith('X_batch') and f.endswith('.npy')],
    key=lambda f: int(re.search(r'\d+', f).group())
)
print(f"Found {len(x_files)} X_batch files (ignoring y_batch label files)")

all_images_list = []

for i, fname in enumerate(x_files):
    arr = np.load(os.path.join(DATA_DIR, fname))   # shape (500, 224, 224, 3), float64

    # Convert to uint8
    if arr.max() <= 1.0:
        arr = (arr * 255.0).astype(np.uint8)
    else:
        arr = arr.astype(np.uint8)

    # Resize each image from 224×224 → 64×64
    resized = np.zeros((len(arr), RESIZE_TO, RESIZE_TO, 3), dtype=np.uint8)
    for j, img in enumerate(arr):
        resized[j] = np.array(
            Image.fromarray(img).resize((RESIZE_TO, RESIZE_TO), Image.BILINEAR)
        )

    all_images_list.append(resized)
    print(f"  [{i+1:2d}/{len(x_files)}] {fname} → resized to {resized.shape}")

all_images = np.concatenate(all_images_list, axis=0)
del all_images_list   # free memory

TOTAL = len(all_images)
IMG_H = all_images.shape[1]   # 64
IMG_W = all_images.shape[2]   # 64
IMG_C = all_images.shape[3]   # 3
N_SRC = IMG_H * IMG_W * IMG_C # 64×64×3 = 12288

print(f"\n✅ Loaded {TOTAL} images | Final shape: {all_images.shape}")
print(f"   N_SRC = {N_SRC} | dtype = {all_images.dtype}")
print(f"   RAM used ≈ {all_images.nbytes / 1024**3:.2f} GB")

import numpy as np
import random

random.seed(42)
np.random.seed(42)

# ── Traditional pipeline ──────────────────────────────────────────────────────
KN_TRAD  = [0.042, 0.083, 0.125, 0.167, 0.25, 0.333, 0.417, 0.5]
SNR_LIST = [0, 10, 20]    # dB
N_EVAL   = 300            # images used for evaluation

# ── Deep JSCC ─────────────────────────────────────────────────────────────────
# Two stride-2 conv layers: 64 → 32 → 16
H_LAT = W_LAT = IMG_H // 4      # = 16

# k/n = C_out × 16 × 16 / 12288 = C_out / 48
C_OUT_FIG3 = [4,    8,     12,    16,    24  ]
KN_FIG3    = [c * H_LAT * W_LAT / N_SRC for c in C_OUT_FIG3]

# Figure 4 config (fixed k/n, varied training SNR)
COUT_FIG4      = [4, 8]
KN_FIG4        = [c * H_LAT * W_LAT / N_SRC for c in COUT_FIG4]
SNR_FIG4_TRAIN = [1, 4, 7, 13, 19]
SNR_FIG4_TEST  = list(range(0, 26))

# ── Training ──────────────────────────────────────────────────────────────────
BATCH_SIZE = 32
EPOCHS     = 30
STEPS      = 200

print("✅ Configuration set!")
print(f"   Traditional k/n : {KN_TRAD}")
print(f"   JSCC k/n        : {[f'{k:.3f}' for k in KN_FIG3]}")
print(f"   JSCC C_out      : {C_OUT_FIG3}")
print(f"   H_LAT = W_LAT   : {H_LAT}")
print(f"   Training        : {EPOCHS} epochs × {STEPS} steps, batch={BATCH_SIZE}")

import io
from PIL import Image
from scipy.special import erfc
import numpy as np

def jpeg_compress(img_u8, max_bytes):
    """Binary-search JPEG quality to fit within max_bytes. Returns bytes or None."""
    if max_bytes < 50:
        return None
    lo, hi, best = 1, 95, None
    while lo <= hi:
        mid = (lo + hi) // 2
        buf = io.BytesIO()
        Image.fromarray(img_u8).save(buf, format='JPEG', quality=mid)
        data = buf.getvalue()
        if len(data) <= max_bytes:
            best = data; lo = mid + 1
        else:
            hi = mid - 1
    return best


def bpsk_ber(snr_db):
    """Uncoded BPSK BER = 0.5 × erfc(√SNR_linear)."""
    return 0.5 * erfc(np.sqrt(10.0 ** (snr_db / 10.0)))


def bpsk_transmit(data_bytes, n_channel_bits, ber):
    """Flip bits with probability BER. Returns corrupted bytes."""
    bits   = np.unpackbits(np.frombuffer(data_bytes, dtype=np.uint8))
    n      = min(len(bits), n_channel_bits)
    bits   = bits[:n]
    errors = np.random.binomial(1, ber, n).astype(np.uint8)
    recv   = np.bitwise_xor(bits, errors)
    return np.packbits(recv).tobytes()


def jpeg_decode(data_bytes, H, W):
    """Safely decode JPEG; return black image if corrupted."""
    try:
        img = Image.open(io.BytesIO(data_bytes))
        img.load()
        arr = np.array(img.convert('RGB'))
        if arr.shape == (H, W, 3):
            return arr.astype(np.float32) / 255.0
    except Exception:
        pass
    return np.zeros((H, W, 3), dtype=np.float32)


def compute_psnr(orig, rec):
    """PSNR between two float32 [0,1] images."""
    mse = float(np.mean((orig - rec) ** 2))
    return 10.0 * np.log10(1.0 / mse) if mse > 1e-10 else 80.0


print("✅ Traditional pipeline functions ready!")
print(f"   BER @ SNR=0dB  : {bpsk_ber(0):.4f}")
print(f"   BER @ SNR=10dB : {bpsk_ber(10):.6f}")
print(f"   BER @ SNR=20dB : {bpsk_ber(20):.8f}")

# ─── CELL 3 (UPDATED) | Configuration ────────────────────────────────────────
import numpy as np, random
random.seed(42); np.random.seed(42)

# Traditional — extended range so JPEG actually works for 64×64 images
KN_TRAD  = [0.25, 0.333, 0.417, 0.5, 0.583, 0.667, 0.75, 1.0]
SNR_LIST = [0, 10, 20]
N_EVAL   = 300

# Deep JSCC
H_LAT = W_LAT = IMG_H // 4     # = 16
C_OUT_FIG3 = [4, 8, 12, 16, 24, 32, 48]
KN_FIG3    = [c * H_LAT * W_LAT / N_SRC for c in C_OUT_FIG3]

COUT_FIG4      = [4, 8]
KN_FIG4        = [c * H_LAT * W_LAT / N_SRC for c in COUT_FIG4]
SNR_FIG4_TRAIN = [1, 4, 7, 13, 19]
SNR_FIG4_TEST  = list(range(0, 26))

BATCH_SIZE = 32
EPOCHS     = 30
STEPS      = 200

print("✅ Config updated!")
print(f"   Traditional k/n (updated): {KN_TRAD}")
print(f"   JSCC k/n                 : {[f'{k:.3f}' for k in KN_FIG3]}")

# ─── CELL 5 | Evaluate Traditional Pipeline ───────────────────────────────────
eval_idx = np.random.choice(TOTAL, N_EVAL, replace=False)
bers     = {s: bpsk_ber(s) for s in SNR_LIST}

acc = {(kn, snr): [] for kn in KN_TRAD for snr in SNR_LIST}

print(f"Evaluating {N_EVAL} images × {len(KN_TRAD)} k/n × {len(SNR_LIST)} SNRs...")
print("(This takes ~2-3 minutes)\n")

for count, idx in enumerate(eval_idx):
    img_u8 = all_images[idx]
    orig   = img_u8.astype(np.float32) / 255.0

    for kn in KN_TRAD:
        n_bits  = max(8, int(kn * N_SRC))
        n_bytes = n_bits // 8
        jdata   = jpeg_compress(img_u8, n_bytes)

        for snr_db in SNR_LIST:
            if jdata is None:
                acc[(kn, snr_db)].append(10.0)
            else:
                trials = []
                for _ in range(3):
                    recv = bpsk_transmit(jdata, n_bits, bers[snr_db])
                    rec  = jpeg_decode(recv, IMG_H, IMG_W)
                    trials.append(compute_psnr(orig, rec))
                acc[(kn, snr_db)].append(float(np.mean(trials)))

    if (count + 1) % 50 == 0:
        print(f"  {count+1}/{N_EVAL} images done...")

trad_results = {}
for snr_db in SNR_LIST:
    trad_results[snr_db] = [float(np.mean(acc[(kn, snr_db)])) for kn in KN_TRAD]
    print(f"SNR={snr_db:2d}dB | {[f'{p:.1f}' for p in trad_results[snr_db]]}")

print("\n✅ Traditional evaluation complete!")

# ─── CELL 6 | Plot Traditional Results (Cliff Effect) ────────────────────────
import matplotlib.pyplot as plt

COLORS  = {0: '#0000BB', 10: '#BB00BB', 20: '#BB0000'}
MARKERS = {0: 'D',       10: 's',       20: 'o'}

plt.figure(figsize=(9, 6))
for snr_db in SNR_LIST:
    plt.plot(KN_TRAD, trad_results[snr_db],
             '--', marker=MARKERS[snr_db], color=COLORS[snr_db],
             linewidth=2, markersize=8,
             label=f'JPEG (SNR={snr_db}dB)')

plt.xlabel('k/n', fontsize=13)
plt.ylabel('PSNR (dB)', fontsize=13)
plt.title('Traditional Communication (JPEG + Uncoded BPSK)\n'
          'PSNR vs k/n — AWGN Channel [Cliff Effect]',
          fontsize=13, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.xlim([0.2, 1.05])
plt.ylim([8, 42])
plt.tight_layout()
plt.savefig('fig_traditional_cliff.png', dpi=150)
plt.show()
print("✅ Saved: fig_traditional_cliff.png")

# ─── CELL 7 | Deep JSCC Architecture (Exact Figure 2 from Paper) ─────────────
import tensorflow as tf
from tensorflow.keras import layers, models

def build_encoder(C_out):
    inp = layers.Input(shape=(IMG_H, IMG_W, IMG_C))
    x   = layers.Lambda(lambda t: t * 2.0 - 1.0)(inp)           # [0,1] → [-1,1]
    x   = layers.Conv2D(16,    5, strides=2, padding='same')(x)  # 64→32
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(32,    5, strides=2, padding='same')(x)  # 32→16
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(32,    5, strides=1, padding='same')(x)  # 16×16×32
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(32,    5, strides=1, padding='same')(x)  # 16×16×32
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(C_out, 5, strides=1, padding='same')(x)  # 16×16×C_out
    out = layers.PReLU(shared_axes=[1, 2])(x)
    return models.Model(inp, out, name=f'Enc_C{C_out}')


def build_decoder(C_out):
    inp = layers.Input(shape=(H_LAT, W_LAT, C_out))
    x   = layers.Conv2DTranspose(32, 5, strides=1, padding='same')(inp)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2DTranspose(32, 5, strides=1, padding='same')(x)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2DTranspose(32, 5, strides=1, padding='same')(x)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2DTranspose(16, 5, strides=2, padding='same')(x)  # 16→32
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    out = layers.Conv2DTranspose(3,  5, strides=2, padding='same',
                                  activation='sigmoid')(x)               # 32→64
    return models.Model(inp, out, name=f'Dec_C{C_out}')


class PowerNorm(layers.Layer):
    """Normalize encoder output to unit average power."""
    def call(self, z):
        return z / tf.sqrt(tf.reduce_mean(tf.square(z)) + 1e-8)


class AWGN(layers.Layer):
    """AWGN Channel: y = z + noise, noise ~ N(0, sigma²)."""
    def __init__(self, snr_db, **kw):
        super().__init__(**kw)
        self.sigma = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
    def call(self, z):
        return z + self.sigma * tf.random.normal(tf.shape(z))


# ── Quick sanity check ────────────────────────────────────────────────────────
_e = build_encoder(8)
_d = build_decoder(8)
print(f"Encoder: {_e.input_shape} → {_e.output_shape}")
print(f"Decoder: {_d.input_shape} → {_d.output_shape}")
del _e, _d
print("✅ Architecture ready!")

# ─── CELL 8 | Data Generator ──────────────────────────────────────────────────
import tensorflow as tf

def jscc_gen(batch_size=32):
    """Stream (img, img) pairs — images normalized to [0,1]."""
    idx = np.arange(TOTAL)
    while True:
        np.random.shuffle(idx)
        for i in range(0, TOTAL - batch_size, batch_size):
            b = all_images[idx[i:i+batch_size]].astype(np.float32) / 255.0
            yield b, b

train_ds = tf.data.Dataset.from_generator(
    lambda: jscc_gen(BATCH_SIZE),
    output_signature=(
        tf.TensorSpec(shape=(BATCH_SIZE, IMG_H, IMG_W, IMG_C), dtype=tf.float32),
        tf.TensorSpec(shape=(BATCH_SIZE, IMG_H, IMG_W, IMG_C), dtype=tf.float32),
    )
).prefetch(tf.data.AUTOTUNE)

print(f"✅ Generator ready | {TOTAL} images | batch={BATCH_SIZE}")

# ─── CELL 9 | Train Deep JSCC — Figure 3 Models ──────────────────────────────
# Add this line at top to fix the missing variable
SNR_FIG3 = SNR_LIST    # [0, 10, 20] dB

def train_jscc(C_out, snr_db, epochs=EPOCHS, steps=STEPS):
    """Build and train one (encoder, decoder) pair."""
    enc = build_encoder(C_out)
    dec = build_decoder(C_out)

    inp    = layers.Input(shape=(IMG_H, IMG_W, IMG_C))
    z      = enc(inp)
    z_norm = PowerNorm()(z)
    y      = AWGN(snr_db)(z_norm)
    out    = dec(y)
    model  = tf.keras.Model(inp, out)
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-4), loss='mse')

    callbacks = [
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor='loss', factor=0.5, patience=5,
            min_lr=1e-7, verbose=0),
        tf.keras.callbacks.EarlyStopping(
            monitor='loss', patience=10,
            restore_best_weights=True, verbose=0),
    ]
    model.fit(train_ds, steps_per_epoch=steps, epochs=epochs,
              callbacks=callbacks, verbose=0)
    return enc, dec


jscc_fig3_models = {}
total_models = len(C_OUT_FIG3) * len(SNR_FIG3)
done = 0

for snr_db in SNR_FIG3:
    for C_out in C_OUT_FIG3:
        kn   = C_out * H_LAT * W_LAT / N_SRC
        done += 1
        print(f"[{done:2d}/{total_models}] Training C_out={C_out} | "
              f"k/n={kn:.3f} | SNR={snr_db}dB ...", end=' ', flush=True)
        enc, dec = train_jscc(C_out, snr_db)
        jscc_fig3_models[(C_out, snr_db)] = (enc, dec)
        print("✅")

print("\n🎉 All Figure 3 models trained!")

# ─── CELL 10 | Evaluate Deep JSCC — Figure 3 ─────────────────────────────────
def eval_jscc(enc, dec, snr_db, n_eval=N_EVAL):
    """Encode → Power Normalize → AWGN at test SNR → Decode → PSNR."""
    sigma  = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
    idx    = np.random.choice(TOTAL, n_eval, replace=False)
    psnrs  = []
    for i in range(0, len(idx), 50):
        batch = all_images[idx[i:i+50]].astype(np.float32) / 255.0
        z     = enc.predict(batch, verbose=0)
        # Power normalize
        z_n   = z / (np.sqrt(np.mean(z**2)) + 1e-8)
        # Add AWGN noise
        y     = z_n + np.random.normal(0, sigma, z_n.shape).astype(np.float32)
        rec   = np.clip(dec.predict(y, verbose=0), 0.0, 1.0)
        for o, r in zip(batch, rec):
            psnrs.append(compute_psnr(o, r))
    return float(np.mean(psnrs))


jscc_fig3_results = {}   # {snr_db: [psnr at each C_out]}

print("Evaluating Deep JSCC (Figure 3)...")
for snr_db in SNR_FIG3:
    row = []
    print(f"\n  SNR = {snr_db} dB:")
    for C_out in C_OUT_FIG3:
        kn       = C_out * H_LAT * W_LAT / N_SRC
        enc, dec = jscc_fig3_models[(C_out, snr_db)]
        p        = eval_jscc(enc, dec, snr_db)   # test at same SNR as train
        row.append(p)
        print(f"    k/n={kn:.3f} (C_out={C_out:2d}) | PSNR = {p:.2f} dB")
    jscc_fig3_results[snr_db] = row

print("\n✅ Deep JSCC Figure 3 evaluation done!")

# ─── CELL 11 | Plot Figure 3 — Traditional + Deep JSCC Combined ──────────────
import matplotlib.pyplot as plt

COLORS  = {0: '#0000BB', 10: '#BB00BB', 20: '#BB0000'}

plt.figure(figsize=(10, 7))

for snr_db in SNR_FIG3:
    c = COLORS[snr_db]

    # Traditional JPEG (dashed) — only plot where we have data
    plt.plot(KN_TRAD, trad_results[snr_db],
             '--', marker='D', color=c, linewidth=2, markersize=7, alpha=0.85,
             label=f'JPEG (SNR={snr_db}dB)')

    # Deep JSCC (solid)
    plt.plot(KN_FIG3, jscc_fig3_results[snr_db],
             '-', marker='o', color=c, linewidth=2.5, markersize=9,
             label=f'Deep JSCC (SNR={snr_db}dB)')

# Annotation for cliff effect and graceful degradation
plt.annotate('JPEG\nCliff Effect\n(Complete Failure)',
             xy=(0.42, 10.5), fontsize=9, color='black',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.8))

plt.annotate('Deep JSCC\nGraceful Degradation',
             xy=(0.09, 24.0), fontsize=9, color='black',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='lightgreen', alpha=0.8))

plt.xlabel('k/n  (Channel uses per source sample)', fontsize=13)
plt.ylabel('PSNR (dB)', fontsize=13)
plt.title('Deep JSCC vs Traditional (JPEG + BPSK)\nPSNR vs k/n — AWGN Channel',
          fontsize=13, fontweight='bold')
plt.legend(fontsize=9, ncol=2, loc='lower right')
plt.grid(True, alpha=0.3)
plt.xlim([0.05, 1.05])
plt.ylim([8, 42])
plt.tight_layout()
plt.savefig('fig3_psnr_vs_kn.png', dpi=150)
plt.show()
print("✅ Saved: fig3_psnr_vs_kn.png")

import matplotlib.pyplot as plt

COLORS  = {0: '#0000BB', 10: '#BB00BB', 20: '#BB0000'}
MARKERS = {0: '*',       10: 's',       20: 'o'}

plt.figure(figsize=(9, 6))

for snr_db in SNR_FIG3:
    plt.plot(KN_FIG3, jscc_fig3_results[snr_db],
             '-', marker=MARKERS[snr_db], color=COLORS[snr_db],
             linewidth=2.5, markersize=9,
             label=f'Deep JSCC (SNR$_{{train}}$={snr_db}dB)')

plt.xlabel('k/n  (Channel uses per source sample)', fontsize=13)
plt.ylabel('PSNR (dB)', fontsize=13)
plt.title('Deep JSCC — PSNR vs k/n\nAWGN Channel | Disaster Management Dataset',
          fontsize=13, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.xlim([0.05, 1])
plt.ylim([24, 30])
plt.tight_layout()
plt.savefig('fig_jscc_only.png', dpi=150)
plt.show()
print("✅ Saved: fig_jscc_only.png")

COLORS  = {0: '#0000BB', 10: '#BB00BB', 20: '#BB0000'}

plt.figure(figsize=(10, 7))

for snr_db in SNR_FIG3:
    c = COLORS[snr_db]
    # Traditional JPEG — dashed
    plt.plot(KN_TRAD, trad_results[snr_db],
             '--', marker='D', color=c, linewidth=2, markersize=7, alpha=0.85,
             label=f'JPEG (SNR={snr_db}dB)')
    # Deep JSCC — solid
    plt.plot(KN_FIG3, jscc_fig3_results[snr_db],
             '-', marker='o', color=c, linewidth=2.5, markersize=9,
             label=f'Deep JSCC (SNR={snr_db}dB)')

plt.annotate('← JPEG Cliff Effect\n   (Complete Failure at\n    low k/n & SNR=0dB)',
             xy=(0.5, 10.5), fontsize=9, color='#880000',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.8))

plt.annotate('Deep JSCC →\nGraceful Degradation\n(works at all k/n)',
             xy=(0.08, 25.5), fontsize=9, color='#000088',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='lightgreen', alpha=0.8))

plt.xlabel('k/n  (Channel uses per source sample)', fontsize=13)
plt.ylabel('PSNR (dB)', fontsize=13)
plt.title('Deep JSCC vs Traditional Communication (JPEG + BPSK)\nPSNR vs k/n — AWGN Channel',
          fontsize=13, fontweight='bold')
plt.legend(fontsize=9, ncol=2, loc='lower right')
plt.grid(True, alpha=0.3)
plt.xlim([0.05, 1.05])
plt.ylim([8, 42])
plt.tight_layout()
plt.savefig('fig3_combined.png', dpi=150)
plt.show()
print("✅ Saved: fig3_combined.png")

# ─── CELL 12 | Train Deep JSCC — Figure 4 Models ─────────────────────────────
# Fixed k/n, multiple training SNRs to show effect of SNR mismatch
# 5 training SNRs × 2 k/n values = 10 models

jscc_fig4_models = {}   # {(C_out, snr_train): (encoder, decoder)}
total_fig4 = len(COUT_FIG4) * len(SNR_FIG4_TRAIN)
done = 0

for C_out in COUT_FIG4:
    kn = C_out * H_LAT * W_LAT / N_SRC
    for snr_train in SNR_FIG4_TRAIN:
        done += 1
        print(f"[{done:2d}/{total_fig4}] Training C_out={C_out} | "
              f"k/n={kn:.3f} | SNR_train={snr_train}dB ...", end=' ', flush=True)
        enc, dec = train_jscc(C_out, snr_train)
        jscc_fig4_models[(C_out, snr_train)] = (enc, dec)
        print("✅")

print("\n🎉 All Figure 4 models trained!")

# ─── CELL 13 | Evaluate + Plot Figure 4 ──────────────────────────────────────
# Evaluate each model at ALL test SNRs (0–25 dB)
jscc_fig4_results = {}   # {(C_out, snr_train): [psnr at each test_snr]}

print("Evaluating Figure 4 models at all test SNRs...")
for C_out in COUT_FIG4:
    for snr_train in SNR_FIG4_TRAIN:
        enc, dec  = jscc_fig4_models[(C_out, snr_train)]
        psnr_list = []
        for snr_test in SNR_FIG4_TEST:
            p = eval_jscc(enc, dec, snr_test, n_eval=200)
            psnr_list.append(p)
        jscc_fig4_results[(C_out, snr_train)] = psnr_list
        print(f"  C_out={C_out} | SNR_train={snr_train:2d}dB | "
              f"PSNR@0dB={psnr_list[0]:.1f} | @25dB={psnr_list[-1]:.1f}")

print("\n✅ Figure 4 evaluation done!")

# ── Plot Figure 4 (two subplots, matching paper Fig 4) ───────────────────────
CURVE_COLORS  = {1:'#0072BD', 4:'#D95319', 7:'#EDB120', 13:'#7E2F8E', 19:'#77AC30'}
CURVE_MARKERS = {1:'*',       4:'o',       7:'s',       13:'D',       19:'^'      }

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

for ax, (C_out, kn_label) in zip(axes, zip(COUT_FIG4, ['1/12', '1/6'])):
    for snr_train in SNR_FIG4_TRAIN:
        psnrs = jscc_fig4_results[(C_out, snr_train)]
        ax.plot(SNR_FIG4_TEST, psnrs,
                color=CURVE_COLORS[snr_train],
                marker=CURVE_MARKERS[snr_train],
                markevery=5, linewidth=2, markersize=8,
                label=f'SNR$_{{train}}$={snr_train}dB')

    ax.set_title(f'AWGN Channel  (k/n = {kn_label})',
                 fontsize=13, fontweight='bold')
    ax.set_xlabel('SNR$_{test}$ (dB)', fontsize=12)
    ax.set_ylabel('PSNR (dB)', fontsize=12)
    ax.legend(fontsize=9, loc='lower right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, 25])

plt.suptitle('Deep JSCC — PSNR vs SNR$_{test}$ for Different Training SNRs\n'
             'Disaster Management Drone Dataset',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('fig4_psnr_vs_snr.png', dpi=150)
plt.show()
print("✅ Saved: fig4_psnr_vs_snr.png")

# ─── CELL 13b | Smoother Figure 4 (500 images + smoothing) ───────────────────
from scipy.ndimage import uniform_filter1d

print("Re-evaluating with 500 images for smoother curves...")
jscc_fig4_results = {}

for C_out in COUT_FIG4:
    for snr_train in SNR_FIG4_TRAIN:
        enc, dec  = jscc_fig4_models[(C_out, snr_train)]
        psnr_list = []
        for snr_test in SNR_FIG4_TEST:
            p = eval_jscc(enc, dec, snr_test, n_eval=500)
            psnr_list.append(p)
        jscc_fig4_results[(C_out, snr_train)] = psnr_list
        print(f"  C_out={C_out} | SNR_train={snr_train:2d}dB | "
              f"@0dB={psnr_list[0]:.1f} | @25dB={psnr_list[-1]:.1f}")

print("\nPlotting...")

CURVE_COLORS  = {1:'#0072BD', 4:'#D95319', 7:'#EDB120', 13:'#7E2F8E', 19:'#77AC30'}
CURVE_MARKERS = {1:'*',       4:'o',       7:'s',       13:'D',       19:'^'      }

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

for ax, (C_out, kn_label) in zip(axes, zip(COUT_FIG4, ['1/12', '1/6'])):
    for snr_train in SNR_FIG4_TRAIN:
        raw    = jscc_fig4_results[(C_out, snr_train)]
        smooth = uniform_filter1d(raw, size=3)   # light smoothing
        ax.plot(SNR_FIG4_TEST, smooth,
                color=CURVE_COLORS[snr_train],
                marker=CURVE_MARKERS[snr_train],
                markevery=5, linewidth=2.2, markersize=9,
                label=f'SNR$_{{train}}$={snr_train}dB')

    ax.set_title(f'AWGN Channel  (k/n = {kn_label})',
                 fontsize=13, fontweight='bold')
    ax.set_xlabel('SNR$_{test}$ (dB)', fontsize=12)
    ax.set_ylabel('PSNR (dB)', fontsize=12)
    ax.legend(fontsize=9, loc='lower right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, 25])

plt.suptitle('Deep JSCC — PSNR vs SNR$_{test}$ for Different Training SNRs\n'
             'Disaster Management Drone Dataset',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('fig4_psnr_vs_snr_smooth.png', dpi=150)
plt.show()
print("✅ Saved: fig4_psnr_vs_snr_smooth.png")

# ─── VISUAL COMPARISON FIGURE (Original | Deep JSCC | JPEG) ──────────────────
from skimage.metrics import structural_similarity as ssim_fn

sample_idx = 42    # change to any number 0-19499 to pick different drone image
img_u8  = all_images[sample_idx]
img_f32 = img_u8.astype(np.float32) / 255.0

SHOW_SNRS = [0, 5, 10, 15, 20]
# ─── Change only these 2 lines and re-run ─────────────────────────────────────
C_SHOW    = 24            # k/n=0.5 → 768 bytes → JPEG actually compresses
kn_show   = C_SHOW * H_LAT * W_LAT / N_SRC   # = 0.5


jscc_recs = []
jpeg_recs = []

for snr_db in SHOW_SNRS:
    enc, dec = jscc_fig3_models.get((C_SHOW, snr_db),
               jscc_fig3_models.get((C_SHOW, 20)))
    sigma  = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
    batch  = img_f32[np.newaxis]
    z      = enc.predict(batch, verbose=0)
    z_n    = z / (np.sqrt(np.mean(z**2)) + 1e-8)
    y      = z_n + np.random.normal(0, sigma, z_n.shape).astype(np.float32)
    rec_j  = np.clip(dec.predict(y, verbose=0)[0], 0.0, 1.0)
    jscc_recs.append(rec_j)

    n_bits = max(8, int(kn_show * N_SRC))
    n_bytes= n_bits // 8
    jdata  = jpeg_compress(img_u8, n_bytes)
    ber    = bpsk_ber(snr_db)
    if jdata is None:
        jpeg_recs.append(np.zeros_like(img_f32))
    else:
        recv  = bpsk_transmit(jdata, n_bits, ber)
        rec_t = jpeg_decode(recv, IMG_H, IMG_W)
        jpeg_recs.append(rec_t)

fig, axes = plt.subplots(len(SHOW_SNRS), 3, figsize=(10, len(SHOW_SNRS) * 3.2))
fig.suptitle(f'Visual Comparison — Deep JSCC vs JPEG+BPSK\n'
             f'k/n={kn_show:.3f} | Disaster Management Drone Dataset',
             fontsize=13, fontweight='bold')

for ax, title in zip(axes[0], ['Original', 'Deep JSCC', 'JPEG + BPSK']):
    ax.set_title(title, fontsize=12, fontweight='bold')

for row, snr_db in enumerate(SHOW_SNRS):
    rec_jscc = jscc_recs[row]
    rec_jpeg = jpeg_recs[row]

    p_jscc = compute_psnr(img_f32, rec_jscc)
    p_jpeg = compute_psnr(img_f32, rec_jpeg)
    s_jscc = ssim_fn(img_f32, rec_jscc, channel_axis=2, data_range=1.0)
    s_jpeg = ssim_fn(img_f32, rec_jpeg, channel_axis=2, data_range=1.0)

    imgs   = [img_f32, rec_jscc, rec_jpeg]
    labels = ['Original',
              f'PSNR={p_jscc:.2f}dB  SSIM={s_jscc:.2f}',
              f'PSNR={p_jpeg:.2f}dB  SSIM={s_jpeg:.2f}']

    for col, (ax, im, lb) in enumerate(zip(axes[row], imgs, labels)):
        ax.imshow(np.clip(im, 0, 1))
        ax.axis('off')
        if col == 0:
            ax.set_ylabel(f'SNR={snr_db}dB', fontsize=11,
                          fontweight='bold', rotation=90, labelpad=10)
        ax.set_xlabel(lb, fontsize=9)

plt.tight_layout()
plt.savefig('fig_visual_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Saved: fig_visual_comparison.png")

# ─── VISUAL COMPARISON — 5 DIFFERENT IMAGES at fixed SNR ─────────────────────
from skimage.metrics import structural_similarity as ssim_fn

# Pick 5 different representative drone images from your dataset
SAMPLE_IDS = [42, 150, 300, 1000, 2500]   # change these to any indices you like
FIXED_SNR  = 10    # fixed test SNR for this comparison
C_SHOW     = 24    # k/n=0.5
kn_show    = C_SHOW * H_LAT * W_LAT / N_SRC  # = 0.5

enc_show, dec_show = jscc_fig3_models[(C_SHOW, FIXED_SNR)]
sigma = float(np.sqrt(1.0 / (2.0 * 10.0 ** (FIXED_SNR / 10.0))))

fig, axes = plt.subplots(len(SAMPLE_IDS), 3,
                         figsize=(10, len(SAMPLE_IDS) * 3.2))
fig.suptitle(f'Visual Comparison — 5 Different Drone Images\n'
             f'k/n={kn_show:.3f} | SNR_test={FIXED_SNR}dB | '
             f'Deep JSCC vs JPEG+BPSK',
             fontsize=13, fontweight='bold')

for ax, title in zip(axes[0], ['Original', 'Deep JSCC', 'JPEG + BPSK']):
    ax.set_title(title, fontsize=12, fontweight='bold')

for row, idx in enumerate(SAMPLE_IDS):
    img_u8  = all_images[idx]
    img_f32 = img_u8.astype(np.float32) / 255.0

    # Deep JSCC
    batch = img_f32[np.newaxis]
    z     = enc_show.predict(batch, verbose=0)
    z_n   = z / (np.sqrt(np.mean(z**2)) + 1e-8)
    y     = z_n + np.random.normal(0, sigma, z_n.shape).astype(np.float32)
    rec_jscc = np.clip(dec_show.predict(y, verbose=0)[0], 0.0, 1.0)

    # JPEG + BPSK
    n_bits  = max(8, int(kn_show * N_SRC))
    n_bytes = n_bits // 8
    jdata   = jpeg_compress(img_u8, n_bytes)
    ber     = bpsk_ber(FIXED_SNR)
    if jdata is None:
        rec_jpeg = np.zeros_like(img_f32)
    else:
        recv     = bpsk_transmit(jdata, n_bits, ber)
        rec_jpeg = jpeg_decode(recv, IMG_H, IMG_W)

    # PSNR / SSIM
    p_jscc = compute_psnr(img_f32, rec_jscc)
    p_jpeg = compute_psnr(img_f32, rec_jpeg)
    s_jscc = ssim_fn(img_f32, rec_jscc, channel_axis=2, data_range=1.0)
    s_jpeg = ssim_fn(img_f32, rec_jpeg, channel_axis=2, data_range=1.0)

    imgs   = [img_f32, rec_jscc, rec_jpeg]
    labels = [f'Image #{idx}',
              f'PSNR={p_jscc:.2f}dB | SSIM={s_jscc:.2f}',
              f'PSNR={p_jpeg:.2f}dB | SSIM={s_jpeg:.2f}']

    for col, (ax, im, lb) in enumerate(zip(axes[row], imgs, labels)):
        ax.imshow(np.clip(im, 0, 1))
        ax.axis('off')
        ax.set_xlabel(lb, fontsize=9)

plt.tight_layout()
plt.savefig('fig_visual_5images.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Saved: fig_visual_5images.png")

# ─── DEEP JSCC-Q Architecture & Quantizers ───────────────────
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

class SoftQuantizer(layers.Layer):
    def __init__(self, M=16, sigma_q=10.0, **kwargs):
        super().__init__(**kwargs)
        self.M = M
        self.sigma_q = sigma_q
        self.constellation = self._generate_mqam(M)

    def _generate_mqam(self, M):
        m = int(np.sqrt(M))
        points = np.arange(-(m - 1), m, 2, dtype=np.float32)
        I, Q = np.meshgrid(points, points)
        const = np.stack([I.flatten(), Q.flatten()], axis=1)
        avg_power = np.mean(np.sum(const**2, axis=1))
        return tf.constant(const / np.sqrt(avg_power))

    def call(self, z):
        shape = tf.shape(z)
        z_flat = tf.reshape(z, [-1, 2])
        const = tf.expand_dims(self.constellation, 0)
        z_ex = tf.expand_dims(z_flat, 1)
        dist = tf.reduce_sum(tf.square(z_ex - const), axis=2)
        weights = tf.nn.softmax(-self.sigma_q * dist, axis=1)
        z_soft = tf.reduce_sum(tf.expand_dims(weights, 2) * const, axis=1)
        return tf.reshape(z_soft, shape)

class HardQuantizer(layers.Layer):
    def __init__(self, M=16, **kwargs):
        super().__init__(**kwargs)
        self.M = M
        self.constellation = self._generate_mqam(M)

    def _generate_mqam(self, M):
        m = int(np.sqrt(M))
        points = np.arange(-(m - 1), m, 2, dtype=np.float32)
        I, Q = np.meshgrid(points, points)
        const = np.stack([I.flatten(), Q.flatten()], axis=1)
        avg_power = np.mean(np.sum(const**2, axis=1))
        return tf.constant(const / np.sqrt(avg_power))

    def call(self, z):
        shape = tf.shape(z)
        z_flat = tf.reshape(z, [-1, 2])
        const = tf.expand_dims(self.constellation, 0)
        z_ex = tf.expand_dims(z_flat, 1)
        dist = tf.reduce_sum(tf.square(z_ex - const), axis=2)
        idx = tf.argmin(dist, axis=1)
        z_hard = tf.gather(self.constellation, idx)
        z_hard = tf.stop_gradient(z_hard - z_flat) + z_flat
        return tf.reshape(z_hard, shape)

class AWGN_Q(layers.Layer):
    def __init__(self, snr_db, **kwargs):
        super().__init__(**kwargs)
        self.snr_db = snr_db

    def call(self, z):
        snr_linear = 10.0 ** (self.snr_db / 10.0)
        noise_std = tf.sqrt(1.0 / (2.0 * snr_linear))
        noise = tf.random.normal(tf.shape(z), stddev=noise_std)
        return z + noise

def build_jscc_q(C_out, snr_db, M=16, is_training=True):
    inp = layers.Input(shape=(IMG_H, IMG_W, IMG_C))
    x   = layers.Lambda(lambda t: t * 2.0 - 1.0)(inp)
    x   = layers.Conv2D(16, 5, strides=2, padding='same')(x)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(32, 5, strides=2, padding='same')(x)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(32, 5, strides=1, padding='same')(x)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(32, 5, strides=1, padding='same')(x)
    x   = layers.PReLU(shared_axes=[1, 2])(x)
    x   = layers.Conv2D(C_out, 5, strides=1, padding='same')(x)
    latent = layers.PReLU(shared_axes=[1, 2])(x)

    if is_training: z = SoftQuantizer(M=M, sigma_q=10.0)(latent)
    else:           z = HardQuantizer(M=M)(latent)

    y = AWGN_Q(snr_db)(z)

    x_dec = layers.Conv2DTranspose(32, 5, strides=1, padding='same')(y)
    x_dec = layers.PReLU(shared_axes=[1, 2])(x_dec)
    x_dec = layers.Conv2DTranspose(32, 5, strides=1, padding='same')(x_dec)
    x_dec = layers.PReLU(shared_axes=[1, 2])(x_dec)
    x_dec = layers.Conv2DTranspose(32, 5, strides=1, padding='same')(x_dec)
    x_dec = layers.PReLU(shared_axes=[1, 2])(x_dec)
    x_dec = layers.Conv2DTranspose(16, 5, strides=2, padding='same')(x_dec)
    x_dec = layers.PReLU(shared_axes=[1, 2])(x_dec)
    out   = layers.Conv2DTranspose(3, 5, strides=2, padding='same', activation='sigmoid')(x_dec)

    enc = models.Model(inp, latent)
    dec = models.Model(y, out)
    full = models.Model(inp, out)
    return full, enc, dec

print("✅ Deep JSCC-Q Architecture Ready!")

# ─── Train Deep JSCC-Q ──────────────────────────────────────────────
def train_jscc_q(C_out, snr_db, M, epochs=EPOCHS, steps=STEPS):
    full, enc, dec = build_jscc_q(C_out, snr_db, M=M, is_training=True)
    full.compile(optimizer=tf.keras.optimizers.Adam(1e-4), loss='mse')
    callbacks = [
        tf.keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.5, patience=5, min_lr=1e-7, verbose=0),
        tf.keras.callbacks.EarlyStopping(monitor='loss', patience=10, restore_best_weights=True, verbose=0)
    ]
    full.fit(train_ds, steps_per_epoch=steps, epochs=epochs, callbacks=callbacks, verbose=0)
    return enc, dec

jscc_q_models = {}
M_values = [16, 64] # Compare 16-QAM and 64-QAM
C_OUT_Q = [8, 16, 24, 32, 48]   # Bandwidth ratios

print("Training Deep JSCC-Q Models...")
for M in M_values:
    for snr_db in [10, 20]:
        for C_out in C_OUT_Q:
            kn = C_out * H_LAT * W_LAT / N_SRC
            print(f"Training QAM={M} | k/n={kn:.3f} | SNR={snr_db}dB ...", end=' ', flush=True)
            enc, dec = train_jscc_q(C_out, snr_db, M)
            jscc_q_models[(C_out, snr_db, M)] = (enc, dec)
            print("✅")

# ─── Evaluate Deep JSCC-Q ───────────────────────────────────────────
def eval_jscc_q(enc, dec, snr_db, M, n_eval=N_EVAL):
    sigma = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
    idx = np.random.choice(TOTAL, n_eval, replace=False)
    psnrs = []
    hq = HardQuantizer(M=M)
    for i in range(0, len(idx), 50):
        batch = all_images[idx[i:i+50]].astype(np.float32) / 255.0
        z = enc.predict(batch, verbose=0)

        # Applies Hard Quantizer properly for evaluation
        z_q = hq(z).numpy()
        y = z_q + np.random.normal(0, sigma, z_q.shape).astype(np.float32)
        rec = np.clip(dec.predict(y, verbose=0), 0.0, 1.0)
        for o, r in zip(batch, rec): psnrs.append(compute_psnr(o, r))
    return float(np.mean(psnrs))

jscc_q_results = {}
print("Evaluating Deep JSCC-Q...")
for M in M_values:
    for snr_db in [10, 20]:
        row = []
        for C_out in C_OUT_Q:
            enc, dec = jscc_q_models[(C_out, snr_db, M)]
            p = eval_jscc_q(enc, dec, snr_db, M)
            row.append(p)
            print(f"  QAM={M} | SNR={snr_db}dB | C_out={C_out} | PSNR = {p:.2f} dB")
        jscc_q_results[(M, snr_db)] = row

#chatgpt code for only one model

# ============================================================
# TRAIN ONE DEEP JSCC-Q MODEL + SAVE TO DRIVE
# ============================================================

from google.colab import drive
import tensorflow as tf
import json
import os
import numpy as np

# ------------------------------------------------------------
# Mount Drive
# ------------------------------------------------------------
drive.mount('/content/drive')

SAVE_DIR = "/content/drive/MyDrive/DeepJSCCQ_Model"
os.makedirs(SAVE_DIR, exist_ok=True)

# ------------------------------------------------------------
# Training Function
# ------------------------------------------------------------
def train_jscc_q(C_out, snr_db, M, epochs=EPOCHS, steps=STEPS):

    full, enc, dec = build_jscc_q(
        C_out,
        snr_db,
        M=M,
        is_training=True
    )

    full.compile(
        optimizer=tf.keras.optimizers.Adam(1e-4),
        loss='mse'
    )

    callbacks = [
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor='loss',
            factor=0.5,
            patience=5,
            min_lr=1e-7,
            verbose=1
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor='loss',
            patience=10,
            restore_best_weights=True,
            verbose=1
        )
    ]

    full.fit(
        train_ds,
        steps_per_epoch=steps,
        epochs=epochs,
        callbacks=callbacks,
        verbose=1
    )

    return enc, dec


# ------------------------------------------------------------
# SINGLE MODEL CONFIG
# ------------------------------------------------------------
C_OUT  = 24
M       = 16
SNR_DB  = 10

print("="*60)
print("Training Deep JSCC-Q")
print(f"C_OUT  = {C_OUT}")
print(f"M      = {M}")
print(f"SNR_DB = {SNR_DB}")
print("="*60)

# ------------------------------------------------------------
# TRAIN
# ------------------------------------------------------------
enc, dec = train_jscc_q(
    C_out=C_OUT,
    snr_db=SNR_DB,
    M=M
)

print("\n✅ Training Finished")

# ------------------------------------------------------------
# SAVE MODELS
# ------------------------------------------------------------
ENC_PATH = f"{SAVE_DIR}/encoder_qam{M}_cout{C_OUT}_snr{SNR_DB}.keras"
DEC_PATH = f"{SAVE_DIR}/decoder_qam{M}_cout{C_OUT}_snr{SNR_DB}.keras"

enc.save(ENC_PATH)
dec.save(DEC_PATH)

# ------------------------------------------------------------
# SAVE CONFIG
# ------------------------------------------------------------
config = {
    "C_OUT": C_OUT,
    "M": M,
    "SNR_DB": SNR_DB,
    "IMG_H": IMG_H,
    "IMG_W": IMG_W,
    "H_LAT": H_LAT,
    "W_LAT": W_LAT
}

with open(f"{SAVE_DIR}/config.json", "w") as f:
    json.dump(config, f, indent=4)

# ------------------------------------------------------------
# VERIFY ENCODER OUTPUT
# ------------------------------------------------------------
sample = all_images[:1].astype(np.float32) / 255.0

z = enc.predict(sample, verbose=0)

print("\nEncoder Output Shape:")
print(z.shape)

print("\nLatent Statistics:")
print("Min :", np.min(z))
print("Max :", np.max(z))
print("Mean:", np.mean(z))

print("\nSaved Successfully:")
print(ENC_PATH)
print(DEC_PATH)

print("\n✅ Model saved to Google Drive")

sample = all_images[0:1].astype(np.float32)/255.0

z = enc.predict(sample, verbose=0)

rec = dec.predict(z, verbose=0)

print(rec.shape)
print(rec.min())
print(rec.max())

# ─── Compare All Three Pipelines ────────────────────────────────────
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 7))

# 1. Traditional (JPEG + BPSK at SNR=10dB)
plt.plot(KN_TRAD, trad_results[10], '--s', color='#0000BB', label='JPEG + BPSK (10dB)', linewidth=2, markersize=8)

# 2. Deep JSCC (Continuous, SNR=10dB)
kn_jscc = [c * H_LAT * W_LAT / N_SRC for c in C_OUT_FIG3]
plt.plot(kn_jscc, jscc_fig3_results[10], '-o', color='#BB0000', label='Deep JSCC (10dB)', linewidth=2, markersize=8)

# 3. Deep JSCC-Q (Discrete Constellation, SNR=10dB)
kn_q = [c * H_LAT * W_LAT / N_SRC for c in C_OUT_Q]
plt.plot(kn_q, jscc_q_results[(16, 10)], '-D', color='#00BB00', label='Deep JSCC-Q (16-QAM, 10dB)', linewidth=2, markersize=8)
plt.plot(kn_q, jscc_q_results[(64, 10)], '-^', color='#00BBBB', label='Deep JSCC-Q (64-QAM, 10dB)', linewidth=2, markersize=8)

plt.xlabel('Bandwidth Ratio (k/n)', fontsize=14)
plt.ylabel('PSNR (dB)', fontsize=14)
plt.title('Comparison: JPEG vs JSCC vs JSCC-Q at SNR = 10dB', fontsize=15, fontweight='bold')
plt.legend(fontsize=12)
plt.grid(True, alpha=0.4)
plt.xlim([0.0, 1.05])
plt.ylim([10, 40])
plt.tight_layout()
plt.savefig('fig_all_pipelines_comparison.png', dpi=150)
plt.show()

# ─── Visual Reconstructions Comparison ──────────────────────────────
import matplotlib.pyplot as plt

def show_visual_reconstructions(img_idx=42, C_out=16, snr_db=10, M=16):
    fig, axes = plt.subplots(1, 4, figsize=(16, 4))

    # 1. Original
    img_u8 = all_images[img_idx]
    orig = img_u8.astype(np.float32) / 255.0
    axes[0].imshow(orig)
    axes[0].set_title("Original Image", fontsize=14)
    axes[0].axis("off")

    # 2. Traditional (JPEG + BPSK)
    kn = C_out * H_LAT * W_LAT / N_SRC
    n_bits  = max(8, int(kn * N_SRC))
    n_bytes = n_bits // 8
    jdata   = jpeg_compress(img_u8, n_bytes)
    if jdata is None:
        rec_jpeg = np.zeros_like(orig)
        axes[1].set_title("JPEG (Failed)", fontsize=14)
    else:
        ber = bpsk_ber(snr_db)
        recv = bpsk_transmit(jdata, n_bits, ber)
        rec_jpeg = jpeg_decode(recv, IMG_H, IMG_W)
        axes[1].set_title(f"JPEG (PSNR: {compute_psnr(orig, rec_jpeg):.2f})", fontsize=14)
    axes[1].imshow(rec_jpeg)
    axes[1].axis("off")

    # Noise model
    sigma = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
    batch = np.expand_dims(orig, axis=0)

    # 3. Deep JSCC (Continuous)
    enc_jscc, dec_jscc = jscc_fig3_models[(C_out, snr_db)]
    z_jscc = enc_jscc.predict(batch, verbose=0)
    z_jscc_n = z_jscc / (np.sqrt(np.mean(z_jscc**2)) + 1e-8)
    y_jscc = z_jscc_n + np.random.normal(0, sigma, z_jscc_n.shape).astype(np.float32)
    rec_jscc = np.clip(dec_jscc.predict(y_jscc, verbose=0)[0], 0.0, 1.0)

    axes[2].imshow(rec_jscc)
    axes[2].set_title(f"Deep JSCC (PSNR: {compute_psnr(orig, rec_jscc):.2f})", fontsize=14)
    axes[2].axis("off")

    # 4. Deep JSCC-Q (Discrete M-QAM)
    enc_q, dec_q = jscc_q_models[(C_out, snr_db, M)]
    hq = HardQuantizer(M=M)
    z_q = enc_q.predict(batch, verbose=0)
    z_hard = hq(z_q).numpy()
    y_q = z_hard + np.random.normal(0, sigma, z_hard.shape).astype(np.float32)
    rec_q = np.clip(dec_q.predict(y_q, verbose=0)[0], 0.0, 1.0)

    axes[3].imshow(rec_q)
    axes[3].set_title(f"JSCC-Q {M}-QAM (PSNR: {compute_psnr(orig, rec_q):.2f})", fontsize=14)
    axes[3].axis("off")

    plt.tight_layout()
    plt.savefig('fig_visual_comparison_JSCCQ.png', dpi=150)
    plt.show()

# Run the visualization!
print("Comparing visual reconstructions at SNR=10dB, C_out=16...")
show_visual_reconstructions(img_idx=100, C_out=16, snr_db=10, M=16)

# ─── CELL A | Traditional Pipeline Evaluation (PSNR + SSIM) ───────────────────
from skimage.metrics import structural_similarity as ssim_fn

trad_eval_idx = np.random.choice(TOTAL, N_EVAL, replace=False)
trad_psnr_metrics = {}
trad_ssim_metrics = {}

print("Re-evaluating Traditional Pipeline for SSIM and PSNR...")
for snr_db in [10]: # We plot for SNR=10dB usually
    trad_psnr_metrics[snr_db] = []
    trad_ssim_metrics[snr_db] = []

    for kn in KN_TRAD:
        n_bits  = max(8, int(kn * N_SRC))
        n_bytes = n_bits // 8
        psnr_trials = []
        ssim_trials = []

        for idx in trad_eval_idx:
            img_u8 = all_images[idx]
            orig   = img_u8.astype(np.float32) / 255.0
            jdata  = jpeg_compress(img_u8, n_bytes)

            if jdata is None:
                psnr_trials.append(10.0)
                ssim_trials.append(0.0)
            else:
                recv = bpsk_transmit(jdata, n_bits, bpsk_ber(snr_db))
                rec  = jpeg_decode(recv, IMG_H, IMG_W)
                psnr_trials.append(compute_psnr(orig, rec))
                ssim_trials.append(ssim_fn(orig, rec, channel_axis=2, data_range=1.0))

        trad_psnr_metrics[snr_db].append(float(np.mean(psnr_trials)))
        trad_ssim_metrics[snr_db].append(float(np.mean(ssim_trials)))

print("✅ Traditional Baseline Metrics Computed!")

# ─── CELL B | Train & Evaluate Deep JSCC (History + SSIM) ─────────────────────
def train_jscc_with_history(C_out, snr_db, epochs=EPOCHS, steps=STEPS):
    enc, dec = build_encoder(C_out), build_decoder(C_out)
    inp    = layers.Input(shape=(IMG_H, IMG_W, IMG_C))
    z      = enc(inp)
    z_norm = PowerNorm()(z)
    y      = AWGN(snr_db)(z_norm)
    out    = dec(y)
    model  = tf.keras.Model(inp, out)
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-4), loss='mse')

    # Notice we capture the 'history' object here!
    history = model.fit(train_ds, steps_per_epoch=steps, epochs=epochs, verbose=0)
    return enc, dec, history.history['loss']

jscc_losses = {}
jscc_psnr_metrics = {}
jscc_ssim_metrics = {}
print("Retraining Deep JSCC to capture loss history & SSIM...")

for snr_db in [10]:
    jscc_psnr_metrics[snr_db] = []
    jscc_ssim_metrics[snr_db] = []
    for C_out in C_OUT_FIG3:
        # 1. Train and save loss curve
        print(f"Training JSCC | C_out={C_out} | SNR={snr_db}dB ...", end=' ')
        enc, dec, losses = train_jscc_with_history(C_out, snr_db)
        jscc_losses[(C_out, snr_db)] = losses

        # 2. Evaluate PSNR and SSIM
        sigma  = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
        psnrs, ssims = [], []
        for i in range(0, len(trad_eval_idx), 50):
            batch = all_images[trad_eval_idx[i:i+50]].astype(np.float32) / 255.0
            z_n   = enc.predict(batch, verbose=0) / (np.sqrt(np.mean(enc.predict(batch, verbose=0)**2)) + 1e-8)
            y     = z_n + np.random.normal(0, sigma, z_n.shape).astype(np.float32)
            rec   = np.clip(dec.predict(y, verbose=0), 0.0, 1.0)
            for o, r in zip(batch, rec):
                psnrs.append(compute_psnr(o, r))
                ssims.append(ssim_fn(o, r, channel_axis=2, data_range=1.0))

        jscc_psnr_metrics[snr_db].append(float(np.mean(psnrs)))
        jscc_ssim_metrics[snr_db].append(float(np.mean(ssims)))
        print("✅")

# ─── CELL C | Train & Evaluate Deep JSCC-Q (History + SSIM) ───────────────────
def train_jscc_q_with_history(C_out, snr_db, M, epochs=EPOCHS, steps=STEPS):
    full, enc, dec = build_jscc_q(C_out, snr_db, M=M, is_training=True)
    full.compile(optimizer=tf.keras.optimizers.Adam(1e-4), loss='mse')
    history = full.fit(train_ds, steps_per_epoch=steps, epochs=epochs, verbose=0)
    return enc, dec, history.history['loss']

jscc_q_losses = {}
jscc_q_psnr_metrics = {}
jscc_q_ssim_metrics = {}
print("Retraining Deep JSCC-Q to capture loss history & SSIM...")

for M in [16, 64]:
    for snr_db in [10]:
        psnr_row, ssim_row = [], []
        for C_out in C_OUT_Q:
            # 1. Train and save loss curve
            print(f"Training JSCC-Q | {M}-QAM | C_out={C_out} | SNR={snr_db}dB ...", end=' ')
            enc, dec, losses = train_jscc_q_with_history(C_out, snr_db, M)
            jscc_q_losses[(C_out, snr_db, M)] = losses

            # 2. Evaluate Evaluate PSNR and SSIM via HardQuantizer
            sigma = float(np.sqrt(1.0 / (2.0 * 10.0 ** (snr_db / 10.0))))
            hq = HardQuantizer(M=M)
            psnrs, ssims = [], []
            for i in range(0, len(trad_eval_idx), 50):
                batch = all_images[trad_eval_idx[i:i+50]].astype(np.float32) / 255.0
                z_hard = hq(enc.predict(batch, verbose=0)).numpy()
                y = z_hard + np.random.normal(0, sigma, z_hard.shape).astype(np.float32)
                rec = np.clip(dec.predict(y, verbose=0), 0.0, 1.0)
                for o, r in zip(batch, rec):
                    psnrs.append(compute_psnr(o, r))
                    ssims.append(ssim_fn(o, r, channel_axis=2, data_range=1.0))

            psnr_row.append(float(np.mean(psnrs)))
            ssim_row.append(float(np.mean(ssims)))
            print("✅")
        jscc_q_psnr_metrics[(M, snr_db)] = psnr_row
        jscc_q_ssim_metrics[(M, snr_db)] = ssim_row

# ─── CELL D | Master Thesis Plots (Reconstruction Accuracy & Epoch Loss) ──────
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# Plot 1: PSNR vs Bandwidth capacity
axes[0].plot(KN_TRAD, trad_psnr_metrics[10], '--s', color='#0000BB', label='JPEG + BPSK', linewidth=2)
axes[0].plot([c * H_LAT * W_LAT / N_SRC for c in C_OUT_FIG3], jscc_psnr_metrics[10], '-o', color='#BB0000', label='Deep JSCC', linewidth=2)
axes[0].plot([c * H_LAT * W_LAT / N_SRC for c in C_OUT_Q], jscc_q_psnr_metrics[(16, 10)], '-D', color='#00BB00', label='Deep JSCC-Q (16-QAM)', linewidth=2)
axes[0].plot([c * H_LAT * W_LAT / N_SRC for c in C_OUT_Q], jscc_q_psnr_metrics[(64, 10)], '-^', color='#00BBBB', label='Deep JSCC-Q (64-QAM)', linewidth=2)
axes[0].set_title("Reconstruction Accuracy (PSNR)", fontsize=14, fontweight='bold')
axes[0].set_xlabel('Bandwidth Ratio (k/n)', fontsize=12)
axes[0].set_ylabel('PSNR (dB)', fontsize=12)
axes[0].set_ylim([10, 40])
axes[0].grid(True, alpha=0.3); axes[0].legend()

# Plot 2: SSIM vs Bandwidth capacity
# Note: SSIM measures perceptual structural similarity (0 to 1). JSCC-Q often shines here!
axes[1].plot(KN_TRAD, trad_ssim_metrics[10], '--s', color='#0000BB', label='JPEG + BPSK', linewidth=2)
axes[1].plot([c * H_LAT * W_LAT / N_SRC for c in C_OUT_FIG3], jscc_ssim_metrics[10], '-o', color='#BB0000', label='Deep JSCC', linewidth=2)
axes[1].plot([c * H_LAT * W_LAT / N_SRC for c in C_OUT_Q], jscc_q_ssim_metrics[(16, 10)], '-D', color='#00BB00', label='Deep JSCC-Q (16-QAM)', linewidth=2)
axes[1].plot([c * H_LAT * W_LAT / N_SRC for c in C_OUT_Q], jscc_q_ssim_metrics[(64, 10)], '-^', color='#00BBBB', label='Deep JSCC-Q (64-QAM)', linewidth=2)
axes[1].set_title("Perceptual Accuracy (MS-SSIM)", fontsize=14, fontweight='bold')
axes[1].set_xlabel('Bandwidth Ratio (k/n)', fontsize=12)
axes[1].set_ylabel('Structural Similarity Index (MS-SSIM)', fontsize=12)
axes[1].set_ylim([0.2, 1.0])
axes[1].grid(True, alpha=0.3); axes[1].legend()

# Plot 3: Training Loss vs Epochs (Showing convergence side by side)
C_plot = 16 # We will look at the loss curve specifically for C_out = 16
epochs_arr = range(1, EPOCHS + 1)
axes[2].plot(epochs_arr, jscc_losses[(C_plot, 10)], '-o', color='#BB0000', label='Deep JSCC (Continuous)', linewidth=2)
axes[2].plot(epochs_arr, jscc_q_losses[(C_plot, 10, 16)], '-D', color='#00BB00', label='Deep JSCC-Q (16-QAM)', linewidth=2)
axes[2].plot(epochs_arr, jscc_q_losses[(C_plot, 10, 64)], '-^', color='#00BBBB', label='Deep JSCC-Q (64-QAM)', linewidth=2)
axes[2].set_title(f"Model Training Convergence (C_out={C_plot})", fontsize=14, fontweight='bold')
axes[2].set_xlabel('Epoch', fontsize=12)
axes[2].set_ylabel('Mean Squared Error (MSE) Loss', fontsize=12)
axes[2].grid(True, alpha=0.3); axes[2].legend()

plt.tight_layout()
plt.savefig('fig_master_metrics.png', dpi=150)
plt.show()
print("✅ Master Thesis Graphs Generated Successfully!")

import tensorflow as tf
import keras

print(tf.__version__)
print(keras.__version__)
print(python3.__version__)

keras.config.enable_unsafe_deserialization()

encoder = keras.models.load_model(
    "/content/drive/MyDrive/DeepJSCCQ_Model/encoder_qam16_cout24_snr10.keras",
    compile=False,
    safe_mode=False
)

print("LOADED")



from google.colab import drive
drive.mount('/content/drive')